name: CI
<<<<<<< HEAD

on:
  push:
    branches: [main, code-smells]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
=======
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restaurar
        run: dotnet restore
      - name: Compilar
        run: dotnet build --no-restore
      - name: Correr pruebas
>>>>>>> origin/main
        run: dotnet test --no-build
